import * as THREE from 'three';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
import {
  GOAL_W, GOAL_H, POST_R, NET_TOP_DEPTH, NET_BOT_DEPTH,
  PITCH_HALF_L, PITCH_HALF_W, WALL_X,
} from '../core/constants.js';

// Sponsor banners for the ad boards, generated by tools/gen-boards.py into
// ./boards/ and found at build time the way the commentator's clips are (see
// view/sfx.js and ADR-0010): import.meta.glob so they ride through `vite
// build`, inside a try/catch so node's missing import.meta.glob gives an empty
// list and every board keeps its flat colour — which is exactly the look the
// game had before any banner existed.
const BOARD_URLS = (() => {
  try {
    const found = import.meta.glob('./boards/*.webp', {
      eager: true, query: '?url', import: 'default',
    });
    return Object.keys(found).sort().map((k) => found[k]);
  } catch {
    return [];
  }
})();

// The board itself, authored in Blender (tools/blender/make-board.py): a dark
// frame around a white face that leans back six degrees, in the two lengths
// the stadium uses. Found the same way as the banners. Until it loads — or
// forever, without the file — each board is the plain box it always was.
const BOARD_GLB = (() => {
  try {
    const found = import.meta.glob('./boards/*.glb', {
      eager: true, query: '?url', import: 'default',
    });
    const urls = Object.keys(found).sort().map((k) => found[k]);
    return urls[0] || null;
  } catch {
    return null;
  }
})();
let boardMeshes = null;   // Promise<{ 'board-6': Mesh, 'board-3.8': Mesh } | null>

function loadBoardMeshes() {
  if (boardMeshes) return boardMeshes;
  boardMeshes = (async () => {
    if (!BOARD_GLB || typeof fetch !== 'function') return null;
    try {
      const { GLTFLoader } = await import('three/addons/loaders/GLTFLoader.js');
      const gltf = await new Promise((ok, fail) => new GLTFLoader().load(BOARD_GLB, ok, undefined, fail));
      // A two-material Blender mesh arrives as a GROUP of two meshes (one per
      // primitive), named for the mesh with a child each for frame and face.
      // Looking for a Mesh called 'board-6' therefore found nothing, and every
      // board stayed a box — caught by the screenshot, not by any test.
      // three.js sanitises node names for property binding: the dot in
      // "board-3.8" does not survive the loader. Match on the prefix.
      const out = {};
      gltf.scene.traverse((o) => {
        if (o.name === 'board-6') out['board-6'] = o;
        else if (/^board-3/.test(o.name)) out['board-3.8'] = o;
      });
      return out['board-6'] && out['board-3.8'] ? out : null;
    } catch (err) {
      // visible from the console: window.__boards.error
      if (typeof window !== 'undefined') window.__boards = { glb: BOARD_GLB, error: String(err) };
      return null;
    }
  })();
  boardMeshes.then((nodes) => {
    if (typeof window !== 'undefined') {
      window.__boards = { ...(window.__boards || {}), glb: BOARD_GLB, loaded: !!nodes };
    }
  });
  return boardMeshes;
}

/**
 * Turn a plain box board into the authored one, keeping its place.
 *
 * The authored mesh carries two materials — frame, then face — and the
 * banner belongs on the face only. The mesh's +Z is the pitch side; `yaw`
 * turns it to look at the pitch from wherever it stands.
 *
 * @param {THREE.Mesh} box the placeholder already in the scene
 * @param {'board-6'|'board-3.8'} which
 * @param {number} yaw radians about Y
 */
/**
 * The boards, as four meshes.
 *
 * Twenty boards were twenty box meshes; dressed from the glTF they became
 * forty (frame + face each) and the render-budget check counted every one,
 * twice more in the shadow pass. They never move and share two materials, so
 * they are built ONCE the glTF and the banners have both arrived: one merged
 * frame mesh, one merged face mesh whose UVs point into a single atlas of all
 * the banners, and the same pair again for the see-through camera-side run.
 * Six banners, one 1024 x 768 canvas, four draw calls for the lot.
 *
 * Until that lands each board is the flat box it always was; without the
 * glTF, forever.
 *
 * @param {THREE.Mesh} box the placeholder already in the scene
 * @param {'board-6'|'board-3.8'} which
 * @param {number} yaw radians about Y
 * @param {number} banner index into BOARD_URLS
 * @param {boolean} seeThrough the camera-side run
 */
const pendingBoards = [];
function dressBoard(box, which, yaw, banner, seeThrough) {
  pendingBoards.push({ box, which, yaw, banner, seeThrough });
}

async function loadBannerAtlas() {
  if (!BOARD_URLS.length || typeof document === 'undefined') return null;
  const loader = new THREE.TextureLoader();
  const imgs = await Promise.all(BOARD_URLS.map((u) => new Promise((ok) => {
    loader.load(u, (t) => ok(t.image), undefined, () => ok(null));
  })));
  const rows = imgs.length;
  const cv = document.createElement('canvas');
  cv.width = 1024; cv.height = 128 * rows;
  const g = cv.getContext('2d');
  if (!g) return null;
  imgs.forEach((im, i) => {
    if (im) g.drawImage(im, 0, i * 128, 1024, 128);
    else { g.fillStyle = '#666'; g.fillRect(0, i * 128, 1024, 128); }
  });
  const tex = new THREE.CanvasTexture(cv);
  tex.colorSpace = THREE.SRGBColorSpace;
  tex.anisotropy = 8;
  tex.wrapS = THREE.ClampToEdgeWrapping;
  tex.wrapT = THREE.ClampToEdgeWrapping;
  tex.flipY = true;
  return { tex, rows };
}

async function buildBoards(scene) {
  const [nodes, atlas] = await Promise.all([loadBoardMeshes(), loadBannerAtlas()]);
  if (!nodes) return;
  const groups = { solid: { frames: [], faces: [] }, glass: { frames: [], faces: [] } };
  const m = new THREE.Matrix4();
  const q = new THREE.Quaternion();
  for (const b of pendingBoards) {
    if (!b.box.parent) continue;
    q.setFromAxisAngle(new THREE.Vector3(0, 1, 0), b.yaw);
    m.compose(b.box.position, q, new THREE.Vector3(1, 1, 1));
    const src = nodes[b.which];
    src.traverse((o) => {
      if (!o.isMesh) return;
      const geo = o.geometry.clone();
      o.updateWorldMatrix(true, false);
      geo.applyMatrix4(o.matrixWorld);   // the node's own transform inside the glTF
      geo.applyMatrix4(m);               // then the board's place in the ground
      const isFace = /face/i.test(o.material?.name || '');
      if (isFace && atlas) {
        // v into this banner's row of the atlas; the glTF face is 0..1
        const uv = geo.getAttribute('uv');
        const row = b.banner % atlas.rows;
        for (let i = 0; i < uv.count; i++) {
          uv.setY(i, (row + uv.getY(i)) / atlas.rows);
        }
        uv.needsUpdate = true;
      }
      (b.seeThrough ? groups.glass : groups.solid)[isFace ? 'faces' : 'frames'].push(geo);
    });
    b.box.parent.remove(b.box);
  }
  const frameSrc = nodes['board-6'].children.find((c) => !/face/i.test(c.material?.name || ''));
  for (const [kind, parts] of Object.entries(groups)) {
    const glass = kind === 'glass';
    const mk = (geos, mat, shadow) => {
      if (!geos.length) return;
      const mesh = new THREE.Mesh(mergeGeometries(geos, false), mat);
      mesh.castShadow = shadow;
      mesh.name = `boards:${kind}`;
      scene.add(mesh);
      for (const g of geos) g.dispose();
    };
    const frameMat = frameSrc ? frameSrc.material.clone() : new THREE.MeshLambertMaterial({ color: 0x0d0f14 });
    const faceMat = atlas
      ? new THREE.MeshBasicMaterial({ map: atlas.tex, color: 0xdedede })
      : new THREE.MeshBasicMaterial({ color: 0x8892a8 });
    if (glass) {
      for (const mat of [frameMat, faceMat]) {
        mat.transparent = true; mat.opacity = 0.3; mat.depthWrite = false;
      }
    }
    mk(parts.frames, frameMat, !glass);
    mk(parts.faces, faceMat, false);
  }
}

const DEFAULT_HALF_W = GOAL_W / 2;

function tubeBetween(a, b, r, material) {
  const dir = new THREE.Vector3().subVectors(b, a);
  const len = dir.length();
  const mesh = new THREE.Mesh(new THREE.CylinderGeometry(r, r, len, 14), material);
  mesh.position.copy(a).addScaledVector(dir, 0.5);
  mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), dir.normalize());
  mesh.castShadow = true;
  return mesh;
}

// Texture spans x in [-15,15], z in [-24,24]; goal lines at z = ±18.
function makePitchTexture() {
  const W = 30, L = 48, S = 1600;
  const cv = document.createElement('canvas');
  cv.width = S * (W / L); cv.height = S;
  const g = cv.getContext('2d');
  const mPerPx = L / S;
  const px = (m) => m / mPerPx;
  const X = (x) => px(x + W / 2), Z = (z) => px(z + L / 2);

  // base + mowing stripes along z, with a soft grain
  for (let i = 0; i < 16; i++) {
    g.fillStyle = i % 2 ? '#2c8a3c' : '#33984a';
    g.fillRect(0, px(i * 3), cv.width, px(3));
  }
  const noise = g.createImageData(cv.width, cv.height);
  // cheap grain: sparse random darkening dots
  for (let i = 0; i < 60000; i++) {
    const x = (Math.random() * cv.width) | 0, y = (Math.random() * cv.height) | 0;
    g.fillStyle = Math.random() > 0.5 ? 'rgba(0,0,0,0.05)' : 'rgba(255,255,255,0.04)';
    g.fillRect(x, y, 2, 2);
  }
  void noise;

  g.strokeStyle = 'rgba(255,255,255,0.92)';
  g.fillStyle = 'rgba(255,255,255,0.92)';
  g.lineWidth = px(0.12);
  // touchlines + goal lines
  g.strokeRect(X(-PITCH_HALF_W), Z(-PITCH_HALF_L),
    px(PITCH_HALF_W * 2), px(PITCH_HALF_L * 2));
  // halfway line + centre circle + spot
  g.beginPath(); g.moveTo(X(-PITCH_HALF_W), Z(0)); g.lineTo(X(PITCH_HALF_W), Z(0)); g.stroke();
  g.beginPath(); g.arc(X(0), Z(0), px(3), 0, Math.PI * 2); g.stroke();
  g.beginPath(); g.arc(X(0), Z(0), px(0.16), 0, Math.PI * 2); g.fill();
  // boxes, spots and arcs at both ends
  for (const s of [-1, 1]) {
    const gl = s * PITCH_HALF_L;
    g.strokeRect(X(-7), Math.min(Z(gl), Z(gl - s * 4.5)), px(14), px(4.5));
    g.strokeRect(X(-4.5), Math.min(Z(gl), Z(gl - s * 1.8)), px(9), px(1.8));
    g.beginPath(); g.arc(X(0), Z(gl - s * 6), px(0.16), 0, Math.PI * 2); g.fill();
    g.beginPath();
    const a0 = s > 0 ? Math.PI * 1.25 : Math.PI * 0.25;
    g.arc(X(0), Z(gl - s * 6), px(2.6), a0, a0 + Math.PI * 0.5);
    g.stroke();
  }
  const tex = new THREE.CanvasTexture(cv);
  tex.colorSpace = THREE.SRGBColorSpace;
  tex.anisotropy = 8;
  return tex;
}

// Goal frames + stanchions for both ends, sized from the match config. Kept
// out of createScene so a lobby can rebuild them when the goal size changes.
export function buildGoalFrames(scene, config) {
  const { goalW, goalH } = config;
  const halfW = goalW / 2;
  const group = new THREE.Group();
  const white = new THREE.MeshStandardMaterial({ color: 0xf5f5f5, roughness: 0.35 });
  const V = (x, y, z) => new THREE.Vector3(x, y, z);
  // Each goal is one mesh. The posts, bar and stanchions were fourteen
  // cylinders apiece — fourteen draw calls, twice, and again in the shadow
  // pass — for a shape that never moves and shares one material.
  for (const end of [-1, 1]) {
    const gz = end * PITCH_HALF_L;
    const back = end * (PITCH_HALF_L + NET_BOT_DEPTH);
    const kink = end * (PITCH_HALF_L + NET_TOP_DEPTH);
    const tubes = [];
    for (const s of [-1, 1]) {
      tubes.push(tubeBetween(V(s * halfW, 0, gz), V(s * halfW, goalH + POST_R, gz), POST_R, white));
      tubes.push(tubeBetween(V(s * halfW, goalH + POST_R, gz), V(s * halfW, goalH - 0.1, kink), 0.028, white));
      tubes.push(tubeBetween(V(s * halfW, goalH - 0.1, kink), V(s * halfW, 0, back), 0.028, white));
    }
    tubes.push(tubeBetween(V(-halfW - POST_R, goalH, gz), V(halfW + POST_R, goalH, gz), POST_R, white));
    const parts = tubes.map((t) => { t.updateMatrix(); return t.geometry.applyMatrix4(t.matrix); });
    const frame = new THREE.Mesh(mergeGeometries(parts, false), white);
    frame.castShadow = true;
    for (const g of parts) g.dispose();
    group.add(frame);
  }
  scene.add(group);
  return {
    group,
    dispose() {
      scene.remove(group);
      for (const m of group.children) m.geometry.dispose();
      group.clear();
      white.dispose();
    },
  };
}

/**
 * The sky: a gradient dome rather than a flat colour.
 *
 * The scene background was one navy; from the broadcast camera that is a void
 * the stands sit in. A dome with a dusk band low down and the night colour
 * overhead gives the floodlight glow something to sit against and the stands a
 * horizon. Vertex colours on an inverted sphere: one draw call, no texture.
 */
function addSkyDome(scene) {
  const geo = new THREE.SphereGeometry(220, 24, 12);
  const pos = geo.getAttribute('position');
  const col = new Float32Array(pos.count * 3);
  const top = new THREE.Color(0x070c1c);
  const mid = new THREE.Color(0x14203f);
  const rim = new THREE.Color(0x3a2a48);   // the dusk band, faintly warm
  const c = new THREE.Color();
  for (let i = 0; i < pos.count; i++) {
    const y = pos.getY(i) / 220;          // -1..1
    const t = Math.max(0, Math.min(1, (y + 0.05) / 0.5));
    if (y < 0.02) c.copy(rim).lerp(mid, Math.max(0, (y + 0.15) / 0.17));
    else c.copy(mid).lerp(top, t);
    col[i * 3] = c.r; col[i * 3 + 1] = c.g; col[i * 3 + 2] = c.b;
  }
  geo.setAttribute('color', new THREE.BufferAttribute(col, 3));
  const dome = new THREE.Mesh(geo, new THREE.MeshBasicMaterial({
    vertexColors: true, side: THREE.BackSide, fog: false, depthWrite: false,
  }));
  dome.name = 'sky';
  dome.renderOrder = -10;
  scene.add(dome);
}

/**
 * What a floodlight looks like at night: a bloom of light at the head — an
 * additive sprite that costs nothing to light, which the bloom pass in main.js
 * then flares.
 */
function addFloodlightGlow(scene, at) {
  const glowTex = (() => {
    if (typeof document === 'undefined') return null;
    const cv = document.createElement('canvas');
    cv.width = cv.height = 128;
    const g = cv.getContext('2d');
    if (!g) return null;
    const grad = g.createRadialGradient(64, 64, 0, 64, 64, 64);
    grad.addColorStop(0, 'rgba(255,246,220,1)');
    grad.addColorStop(0.25, 'rgba(255,240,200,0.55)');
    grad.addColorStop(1, 'rgba(255,236,190,0)');
    g.fillStyle = grad;
    g.fillRect(0, 0, 128, 128);
    const t = new THREE.CanvasTexture(cv);
    t.colorSpace = THREE.SRGBColorSpace;
    return t;
  })();
  if (glowTex) {
    const glow = new THREE.Sprite(new THREE.SpriteMaterial({
      map: glowTex, blending: THREE.AdditiveBlending, depthWrite: false,
      transparent: true, opacity: 0.9, fog: false,
    }));
    glow.scale.set(7, 7, 1);
    glow.position.copy(at);
    scene.add(glow);
  }
  // No beam cones. A first pass drew a faint additive cone from each head to
  // the centre circle and the broadcast camera showed four hard-edged wedges
  // lying across the pitch; the glow at the head, flared by the bloom pass, is
  // what reads as a floodlight from that camera.
}

function addStadium(scene) {
  // Concrete and seat rows rather than two navies: the stands were reading
  // as a void the crowd floated in, and under the warm key light a mid grey
  // gives the terraces edges and the crowd a floor to sit on.
  const standMat = new THREE.MeshLambertMaterial({ color: 0x4a4f5c });
  const seatMat = new THREE.MeshLambertMaterial({ color: 0x3a4460 });
  // tiered stands: far touchline + both goal ends. The near (+x) side is
  // deliberately open — broadcast style — so the camera always sees the
  // bottom of the pitch; only the ad boards line that edge.
  for (const side of [-1, 1]) {
    for (let t = 0; t < 3; t++) {
      if (side < 0) {
        const s = new THREE.Mesh(new THREE.BoxGeometry(2.2, 1.6 + t * 0.4, 52), t % 2 ? seatMat : standMat);
        s.position.set(side * (14.5 + t * 2.3), (1.6 + t * 0.4) / 2 + t * 1.1, 0);
        scene.add(s);
      }
      const e = new THREE.Mesh(new THREE.BoxGeometry(34, 1.6 + t * 0.4, 2.2), t % 2 ? seatMat : standMat);
      e.position.set(0, (1.6 + t * 0.4) / 2 + t * 1.1, side * (23.5 + t * 2.3));
      scene.add(e);
    }
  }
  // The shell behind the terraces: a back wall the crowd sits against, a roof
  // lip over the top tier, and a run of small lamps under the lip. Without
  // these the stands were three steps floating in the night; the wall gives
  // them a back, the lip a top edge the key light catches, and the lamps —
  // unlit material, so the bloom pass flares them — the lit rim every ground
  // has at night. The camera side stays open, as it always has.
  const wallMat = new THREE.MeshLambertMaterial({ color: 0x3a3f4d });
  const lipMat = new THREE.MeshLambertMaterial({ color: 0x5a6070 });
  const lampMat = new THREE.MeshBasicMaterial({ color: 0xfff2d2 });
  const topY = 1.6 + 2 * 0.4 + 2 * 1.1;        // top of the third tier
  const wallH = 4.2;
  // Every piece of the shell is static and shares one of three materials, so
  // the pieces are merged into three meshes — three draw calls for the whole
  // shell instead of one per lamp. The first version was 35 meshes and the
  // render-budget check counted every one of them.
  const walls = [];
  const lips = [];
  const lamps = [];
  const boxAt = (w, h, d, x, y, z) => {
    const g = new THREE.BoxGeometry(w, h, d);
    g.translate(x, y, z);
    return g;
  };
  const shell = (len, cx, cz, alongZ) => {
    walls.push(boxAt(alongZ ? 0.6 : len, wallH, alongZ ? len : 0.6, cx, topY + wallH / 2 - 0.4, cz));
    // the lip hangs over the crowd, toward the pitch
    const inward = alongZ ? -Math.sign(cx) : -Math.sign(cz);
    lips.push(boxAt(
      alongZ ? 3.4 : len + 1.2, 0.35, alongZ ? len + 1.2 : 3.4,
      cx + (alongZ ? inward * 1.4 : 0), topY + wallH - 0.4, cz + (alongZ ? 0 : inward * 1.4),
    ));
    // lamps under the lip, every 4 m
    const n = Math.floor(len / 4);
    for (let i = 0; i < n; i++) {
      const o = (i - (n - 1) / 2) * 4;
      lamps.push(boxAt(
        alongZ ? 0.5 : 1.2, 0.12, alongZ ? 1.2 : 0.5,
        cx + (alongZ ? inward * 2.6 : o), topY + wallH - 0.62, cz + (alongZ ? o : inward * 2.6),
      ));
    }
  };
  shell(52, -(14.5 + 2 * 2.3 + 1.1), 0, true);              // far touchline
  for (const side of [-1, 1]) shell(34, 0, side * (23.5 + 2 * 2.3 + 1.1), false);   // both ends
  for (const [parts, mat, shadow] of [[walls, wallMat, false], [lips, lipMat, true], [lamps, lampMat, false]]) {
    const merged = new THREE.Mesh(mergeGeometries(parts, false), mat);
    merged.castShadow = shadow;
    scene.add(merged);
    for (const g of parts) g.dispose();
  }

  // floodlight pylons
  const poleMat = new THREE.MeshLambertMaterial({ color: 0x8b94a8 });
  const headMat = new THREE.MeshBasicMaterial({ color: 0xfff6d8 });
  for (const sx of [-1, 1]) for (const sz of [-1, 1]) {
    const pole = new THREE.Mesh(new THREE.CylinderGeometry(0.12, 0.16, 14, 8), poleMat);
    pole.position.set(sx * 13.5, 7, sz * 22.5);
    scene.add(pole);
    const head = new THREE.Mesh(new THREE.BoxGeometry(1.8, 0.9, 0.3), headMat);
    head.position.set(sx * 13.5, 14.2, sz * 22.5);
    head.lookAt(0, 0, 0);
    scene.add(head);
    addFloodlightGlow(scene, head.position);
  }
  // ad boards sit flush with the invisible walls, right behind the lines,
  // so wall rebounds visibly come off the boards
  const colors = [0x1c3f8f, 0x8f1c2e, 0x1c8f5a, 0xa8781c];
  const along = new THREE.BoxGeometry(6, 0.75, 0.1);
  const across = new THREE.BoxGeometry(0.1, 0.75, 6);
  const endBoard = new THREE.BoxGeometry(3.8, 0.75, 0.1);
  let ci = 0;
  for (const side of [-1, 1]) {
    // touchline boards at the side walls; the near (+x, camera-side) run is
    // translucent so it never hides the ball along the bottom touchline
    for (let z = -18; z < 18; z += 6) {
      // Unlit on purpose: a perimeter board is an LED panel, lit from within,
      // and the key light comes from behind the far run anyway — with Lambert
      // the banners on that side went grey.
      const mat = new THREE.MeshBasicMaterial({ color: colors[ci % 4] });
      if (side > 0) {
        mat.transparent = true;
        mat.opacity = 0.3;
        mat.depthWrite = false;
      }
      const b = new THREE.Mesh(across, mat);
      b.position.set(side * (WALL_X + 0.06), 0.38, z + 3);
      b.castShadow = side < 0;
      scene.add(b);
      // -x side faces +x (yaw +90°), +x side faces -x (yaw -90°)
      dressBoard(b, 'board-6', side < 0 ? Math.PI / 2 : -Math.PI / 2, ci++, side > 0);
    }
    // goal-line boards from each post out to the side walls
    for (const sx of [-1, 1]) {
      for (let i = 0; i < 2; i++) {
        const mat = new THREE.MeshBasicMaterial({ color: colors[ci % 4] });
        const b = new THREE.Mesh(endBoard, mat);
        b.position.set(sx * (3.85 + 1.9 + i * 3.8), 0.38, side * (PITCH_HALF_L + 0.12));
        b.castShadow = true;
        scene.add(b);
        // the -z end faces +z (yaw 0), the +z end faces -z (yaw 180°)
        dressBoard(b, 'board-3.8', side < 0 ? 0 : Math.PI, ci++, false);
      }
    }
  }
  buildBoards(scene);
}

export function createScene(container) {
  const renderer = new THREE.WebGLRenderer({ antialias: true });
  renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
  renderer.setSize(innerWidth, innerHeight);
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE.PCFSoftShadowMap;
  renderer.toneMapping = THREE.ACESFilmicToneMapping;
  container.appendChild(renderer.domElement);

  const scene = new THREE.Scene();
  scene.background = new THREE.Color(0x0b1226);
  scene.fog = new THREE.Fog(0x0b1226, 60, 160);
  addSkyDome(scene);

  const camera = new THREE.PerspectiveCamera(50, innerWidth / innerHeight, 0.1, 300);
  camera.position.set(28, 23, 0);
  camera.lookAt(0, 0, 0);

  // A night match under floodlights, not a day under a sun. The key light is
  // the warm white of a floodlight bank and comes in low from the stand side
  // so faces and the near side of every player catch it; a cool, dim fill
  // from the opposite corner keeps the shadow side readable instead of black.
  // The hemisphere is the sky glow over the pitch's own green bounce.
  scene.add(new THREE.HemisphereLight(0x8fa8d8, 0x1d4a26, 0.72));
  const sun = new THREE.DirectionalLight(0xfff0cf, 2.1);
  sun.position.set(-22, 30, 14);
  sun.castShadow = true;
  sun.shadow.mapSize.set(2048, 2048);
  sun.shadow.camera.left = -30; sun.shadow.camera.right = 30;
  sun.shadow.camera.top = 30; sun.shadow.camera.bottom = -30;
  sun.shadow.camera.far = 90;
  sun.shadow.bias = -0.0004;
  sun.shadow.radius = 3;
  scene.add(sun);
  const fill = new THREE.DirectionalLight(0x6f86c9, 0.6);
  fill.position.set(26, 18, -20);
  scene.add(fill);
  renderer.toneMappingExposure = 1.15;

  const ground = new THREE.Mesh(
    new THREE.PlaneGeometry(30, 48),
    new THREE.MeshLambertMaterial({ map: makePitchTexture() }),
  );
  ground.rotation.x = -Math.PI / 2;
  ground.receiveShadow = true;
  scene.add(ground);
  const apron = new THREE.Mesh(
    new THREE.PlaneGeometry(400, 400),
    new THREE.MeshLambertMaterial({ color: 0x101c2e }),
  );
  apron.rotation.x = -Math.PI / 2;
  apron.position.y = -0.02;
  scene.add(apron);

  // goal frames are built separately by buildGoalFrames(scene, config)

  addStadium(scene);
  // no cage: the low ad boards are the boundary, high balls go out of play

  const onResize = () => {
    camera.aspect = innerWidth / innerHeight;
    camera.updateProjectionMatrix();
    renderer.setSize(innerWidth, innerHeight);
  };
  addEventListener('resize', onResize);

  return { renderer, scene, camera };
}
