// Placeholder commentary clips (feature matrix #38).
//
//   node packages/client/src/arena/present/tools/make-clips.mjs
//   npm run present:clips
//
// We have no recorded commentary and will not have any until a human sits in
// front of a microphone (brain/40-progress/HUMAN-QUEUE.md). Shipping the
// pipeline untested until then would mean discovering every timing, ducking and
// interruption bug on the day the real audio arrives, so this writes one WAV per
// manifest entry with EXACTLY the declared duration and a distinct, obviously
// synthetic sound. The mix, the ducking, the cooldowns and the interruptions are
// therefore exercised end to end today; replacing the files with real takes
// changes nothing but the timbre.
//
// The files are deliberately NOT committed (see clips/.gitignore): they are
// derived, they are noise, and a fresh checkout that has not run this script
// simply plays silence with correct timing.
//
// Format: 8 kHz, mono, 8-bit unsigned PCM WAV. Smallest thing a browser will
// decode without a codec, and small enough that 60 of them cost under a
// megabyte. Real recordings should be OPUS (or MP3); the manifest lists those
// extensions ahead of .wav, so dropping them in wins automatically.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CLIP_MANIFEST, recordingSheet, validateManifest } from '../manifest.js';
import { LINES } from '../lines.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const CLIP_DIR = resolve(HERE, '..', 'clips');
const RATE = 8000;

/** Stable per-id pitch, so every line is recognisable while you debug. */
function hash(s) {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i) & 0xff;
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h >>> 0;
}

/**
 * A speech-shaped placeholder: a carrier tone chopped into "syllables" with an
 * envelope, then a short tail of silence. It reads as "someone is talking" at a
 * glance on a waveform, which is what you want when you are checking whether a
 * goal line cut a tackle line off in the right place.
 */
function renderClip(id, lang, durationMs) {
  const samples = Math.round((durationMs / 1000) * RATE);
  const data = Buffer.alloc(samples, 128);
  const h = hash(`${id}.${lang}`);
  const base = 90 + (h % 70) + (lang === 'en' ? 35 : 0); // Hz
  const syllable = 0.16 + ((h >>> 8) % 7) / 100; // seconds
  const tailMs = 180;
  const voiced = Math.max(0, samples - Math.round((tailMs / 1000) * RATE));
  for (let i = 0; i < voiced; i++) {
    const t = i / RATE;
    const phase = (t % syllable) / syllable;
    // one envelope per syllable, plus a gap every fourth one for a breath
    const gap = Math.floor(t / syllable) % 4 === 3 ? 0.25 : 1;
    const env = Math.sin(Math.PI * phase) ** 1.5 * gap;
    const wobble = 1 + 0.06 * Math.sin(2 * Math.PI * 3.1 * t);
    const s =
      0.6 * Math.sin(2 * Math.PI * base * wobble * t) +
      0.25 * Math.sin(2 * Math.PI * base * 2 * wobble * t) +
      0.15 * Math.sin(2 * Math.PI * base * 3 * wobble * t);
    data[i] = Math.max(0, Math.min(255, Math.round(128 + s * env * 90)));
  }
  return wav(data);
}

function wav(pcm) {
  const header = Buffer.alloc(44);
  header.write('RIFF', 0);
  header.writeUInt32LE(36 + pcm.length, 4);
  header.write('WAVE', 8);
  header.write('fmt ', 12);
  header.writeUInt32LE(16, 16); // PCM chunk size
  header.writeUInt16LE(1, 20); // format: PCM
  header.writeUInt16LE(1, 22); // channels
  header.writeUInt32LE(RATE, 24);
  header.writeUInt32LE(RATE, 28); // byte rate = rate * channels * bytes
  header.writeUInt16LE(1, 32); // block align
  header.writeUInt16LE(8, 34); // bits per sample
  header.write('data', 36);
  header.writeUInt32LE(pcm.length, 40);
  return Buffer.concat([header, pcm]);
}

export function generate(dir = CLIP_DIR) {
  const issues = validateManifest();
  if (issues.length) {
    for (const i of issues) console.error(`FAIL ${i}`);
    throw new Error(`clip manifest has ${issues.length} problems`);
  }
  mkdirSync(dir, { recursive: true });
  const written = [];
  for (const entry of Object.values(CLIP_MANIFEST.entries)) {
    const buf = renderClip(entry.id, entry.lang, entry.durationMs);
    writeFileSync(resolve(dir, entry.file), buf);
    written.push({ file: entry.file, bytes: buf.length, ms: entry.durationMs });
  }
  writeFileSync(
    resolve(dir, 'manifest.json'),
    `${JSON.stringify({
      ...CLIP_MANIFEST,
      note: 'generated by tools/make-clips.mjs from lines.js — do not hand-edit',
      sheet: recordingSheet(),
    }, null, 2)}\n`,
  );
  return written;
}

/** The markdown block HUMAN-QUEUE.md carries. Printed with --sheet. */
export function sheetMarkdown() {
  const rows = recordingSheet();
  const out = [
    '| dosya | dil | sn | olay | metin |',
    '|---|---|---|---|---|',
  ];
  for (const r of rows) {
    out.push(`| \`${r.file}\` | ${r.lang} | ${r.seconds} | ${r.event} | ${r.text.replace(/\|/g, '\\|')} |`);
  }
  return out.join('\n');
}

if (process.argv[1] && process.argv[1].endsWith('make-clips.mjs')) {
  if (process.argv.includes('--sheet')) {
    console.log(sheetMarkdown());
  } else {
    const written = generate();
    const bytes = written.reduce((a, w) => a + w.bytes, 0);
    const seconds = written.reduce((a, w) => a + w.ms, 0) / 1000;
    console.log(
      `wrote ${written.length} placeholder clips for ${LINES.length} lines `
      + `(${seconds.toFixed(1)} s, ${(bytes / 1024).toFixed(0)} KiB) into ${CLIP_DIR}`,
    );
    console.log('these are NOT recordings — see brain/40-progress/HUMAN-QUEUE.md');
  }
}
