"""Q16.16 signed fixed-point arithmetic, mirroring packages/core/src/fx.js.

Every function here is a transcription of its JS twin, not an equivalent. The
JS side is the specification and this module is the port, so where the two
could differ the comment says which JS line forced the Python shape.

Representation
    value = raw / 2**16, raw stored as a signed 32-bit integer
    range  [-32768, 32767.99998], resolution 1/65536

Rules of the house (ADR-0003, and enforced by test_parity.py against fixtures
generated by fx.js itself)
    * every operator saturates instead of wrapping
    * multiplication and division truncate toward zero
    * from_number / to_number are the only float boundary

Why the JS is portable at all, and what that means here
    fxMul splits both operands into 16-bit limbs so every partial product stays
    an exact integer below 2**53, which is the range where an IEEE-754 double
    is an exact integer. Python's int has no such ceiling, so the limb split is
    not needed for exactness in Python -- but it IS needed for equality,
    because the limb form also decides where the truncation happens. The port
    therefore keeps the limbs.

    fxDiv in JS estimates the quotient with a double division and then corrects
    it against an exactly recomputed remainder. Python's ``//`` is already the
    exact floored quotient of non-negative operands, so the correction is a
    no-op; the port uses ``//`` and the fixture test proves the two agree on
    every recorded pair.

    isqrtInt is a restoring digit-by-digit square root in JS, chosen so no
    Math.sqrt seed can leak an engine's rounding in. It computes exactly
    floor(sqrt(v)) for 0 <= v <= 2**53, which is what math.isqrt computes for
    every non-negative int. The port uses math.isqrt and the fixture test
    compares both against the JS output.

Vectorisation
    The scalar functions take and return Python ints. The ``v_`` family takes
    and returns numpy int64 arrays and performs the SAME limb arithmetic
    elementwise. int64 is wide enough for every intermediate the scalar path
    produces (the largest is |ah*bh*2**16| < 2**47), so the vector path is not
    an approximation of the scalar path: it is the same integer expression
    evaluated on many lanes. test_parity.py runs the whole 3000-tick scenario
    through both and compares the checksum chains.
"""

from __future__ import annotations

import math

import numpy as np

FX_SHIFT = 16
FX_SCALE = 65536  # 2**16
FX_ONE = 65536
FX_HALF = 32768
FX_MAX = 2147483647  # 32767.99998
FX_MIN = -2147483648  # -32768
FX_EPS = 1

# Largest magnitude whose square still lands inside the exact-integer range of
# a double. Kept even though Python ints are exact: fxHypot's halving loop is
# part of the result, not part of the overflow protection.
HYPOT_SAFE = 67108864  # 2**26 raw = 1024.0

_TWO31 = 2147483648


# ---------------------------------------------------------------- boundary


def js_round(x: float) -> int:
    """ECMAScript ``Math.round``: nearest integer, ties toward +infinity.

    Not ``round()`` (banker's rounding) and not ``floor(x + 0.5)``: the latter
    disagrees with V8 for 0.49999999999999994, where ``x + 0.5`` rounds up to
    exactly 1.0 in float64 but the true nearest integer is 0.
    """
    if not math.isfinite(x):
        return 0
    f = math.floor(x)
    diff = x - f
    if diff > 0.5:
        return f + 1
    if diff < 0.5:
        return f
    return f + 1  # tie -> toward +infinity, matching the spec


def from_number(n: float) -> int:
    """Float -> fixed. Authoring / input boundary only."""
    if not isinstance(n, (int, float)) or not math.isfinite(n):
        return 0
    r = js_round(n * FX_SCALE)
    if r > FX_MAX:
        return FX_MAX
    if r < FX_MIN:
        return FX_MIN
    return r


def to_number(a: int) -> float:
    """Fixed -> float. Rendering / reporting boundary only."""
    return int(a) / FX_SCALE


def from_int(n: int) -> int:
    """Integer -> fixed, saturating."""
    r = int(n) * FX_SCALE
    if r > FX_MAX:
        return FX_MAX
    if r < FX_MIN:
        return FX_MIN
    return r


def to_int(a: int) -> int:
    """Fixed -> integer, truncating toward zero."""
    a = int(a)
    return -((-a) // FX_SCALE) if a < 0 else a // FX_SCALE


# ---------------------------------------------------------------- core ops


def add(a: int, b: int) -> int:
    s = int(a) + int(b)
    if s > FX_MAX:
        return FX_MAX
    if s < FX_MIN:
        return FX_MIN
    return s


def sub(a: int, b: int) -> int:
    s = int(a) - int(b)
    if s > FX_MAX:
        return FX_MAX
    if s < FX_MIN:
        return FX_MIN
    return s


def neg(a: int) -> int:
    a = int(a)
    return FX_MAX if a == FX_MIN else -a


def fabs(a: int) -> int:
    a = int(a)
    if a < 0:
        return FX_MAX if a == FX_MIN else -a
    return a


def sign(a: int) -> int:
    a = int(a)
    return 1 if a > 0 else (-1 if a < 0 else 0)


def mul(a: int, b: int) -> int:
    """(a * b) >> 16, truncating toward zero, saturating.

    The limb split is fx.js's, kept verbatim: ``(al * bl) >>> 16`` floors the
    low term, and because the operands were made non-negative first, flooring
    the magnitude is truncation toward zero for the signed result.
    """
    a = int(a)
    b = int(b)
    negative = (a < 0) != (b < 0)
    ua = -a if a < 0 else a
    ub = -b if b < 0 else b
    ah = ua // FX_SCALE
    al = ua - ah * FX_SCALE
    bh = ub // FX_SCALE
    bl = ub - bh * FX_SCALE
    mag = ah * bh * FX_SCALE + ah * bl + al * bh + ((al * bl) >> FX_SHIFT)
    if negative:
        return FX_MIN if mag >= _TWO31 else -mag
    return FX_MAX if mag > FX_MAX else mag


def div(a: int, b: int) -> int:
    """(a << 16) / b, truncated toward zero, saturating. b == 0 saturates."""
    a = int(a)
    b = int(b)
    if b == 0:
        return FX_MAX if a > 0 else (FX_MIN if a < 0 else 0)
    if a == 0:
        return 0
    negative = (a < 0) != (b < 0)
    ua = -a if a < 0 else a
    ub = -b if b < 0 else b
    q = (ua * FX_SCALE) // ub  # exact; the JS remainder correction is built in
    if negative:
        return FX_MIN if q >= _TWO31 else -q
    return FX_MAX if q > FX_MAX else q


def fmin(a: int, b: int) -> int:
    return int(a) if int(a) < int(b) else int(b)


def fmax(a: int, b: int) -> int:
    return int(a) if int(a) > int(b) else int(b)


def clamp(a: int, lo: int, hi: int) -> int:
    a = int(a)
    if a < lo:
        return int(lo)
    if a > hi:
        return int(hi)
    return a


# ------------------------------------------------------------------ roots


def isqrt_int(v: int) -> int:
    """Exact floor(sqrt(v)) for a non-negative integer. 0 for v <= 0."""
    v = int(v)
    if v <= 0:
        return 0
    return math.isqrt(v)


def sqrt(a: int) -> int:
    """sqrt of a fixed-point value; negatives clamp to 0. Error < 1 LSB."""
    a = int(a)
    if a <= 0:
        return 0
    return isqrt_int(a * FX_SCALE)


def hypot(x: int, y: int) -> int:
    """sqrt(x*x + y*y) in raw units, with fx.js's halving fallback."""
    x = int(x)
    y = int(y)
    ax = -x if x < 0 else x
    ay = -y if y < 0 else y
    if ax == 0:
        return FX_MAX if ay > FX_MAX else ay
    if ay == 0:
        return FX_MAX if ax > FX_MAX else ax
    shift = 0
    while ax > HYPOT_SAFE or ay > HYPOT_SAFE:
        ax = ax // 2
        ay = ay // 2
        shift += 1
    r = isqrt_int(ax * ax + ay * ay)
    r <<= shift
    return FX_MAX if r > FX_MAX else r


def normalize(x: int, y: int) -> tuple[int, int, int]:
    """Unit vector of (x, y) plus the original length. Zero-length stays zero."""
    length = hypot(x, y)
    if length == 0:
        return 0, 0, 0
    return div(x, length), div(y, length), length


# --------------------------------------------------------------- angles

FX_PI = 205887
FX_TWO_PI = 411775
FX_HALF_PI = 102944

# atan(2**-i) in Q16.16, copied from fx.js rather than recomputed with atan.
CORDIC_ATAN = (
    51472,
    30386,
    16055,
    8150,
    4091,
    2047,
    1024,
    512,
    256,
    128,
    64,
    32,
    16,
    8,
    4,
    2,
)
CORDIC_K = 39797


def _int32(v: int) -> int:
    """JS ``| 0``: wrap into a signed 32-bit integer."""
    v &= 0xFFFFFFFF
    return v - 0x100000000 if v >= 0x80000000 else v


def wrap_angle(a: int) -> int:
    """Wrap a Q16.16 radian angle into [-pi, pi)."""
    a = int(a)
    if -FX_PI <= a < FX_PI:
        return a
    k = math.floor((a + FX_PI) / FX_TWO_PI)
    return _int32(a - k * FX_TWO_PI)


def sin_cos(angle: int) -> tuple[int, int]:
    """(cos, sin) of a Q16.16 radian angle. 16-iteration CORDIC, shifts only.

    ``x >> i`` in JS is an arithmetic shift on a signed 32-bit int, which is
    exactly Python's ``>>`` on a negative int (both floor), so no conversion is
    needed inside the loop; the values stay well inside int32 throughout.
    """
    z = wrap_angle(angle)
    flip = 1
    if z > FX_HALF_PI:
        z = z - FX_PI
        flip = -1
    elif z < -FX_HALF_PI:
        z = z + FX_PI
        flip = -1
    x = CORDIC_K
    y = 0
    for i in range(16):
        dx = x >> i
        dy = y >> i
        if z >= 0:
            nx = x - dy
            y = y + dx
            x = nx
            z -= CORDIC_ATAN[i]
        else:
            nx = x + dy
            y = y - dx
            x = nx
            z += CORDIC_ATAN[i]
    return _int32(flip * x), _int32(flip * y)


def cos(angle: int) -> int:
    return sin_cos(angle)[0]


def sin(angle: int) -> int:
    return sin_cos(angle)[1]


# ------------------------------------------------------------- vectorised
#
# Same expressions, elementwise, on numpy int64. int64 holds every intermediate
# the scalar path produces (|ah*bh*2**16| < 2**47 and ua*2**16 <= 2**47), so
# these are not approximations: they are the identical integer program.


def v_add(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return np.clip(np.asarray(a, np.int64) + np.asarray(b, np.int64), FX_MIN, FX_MAX)


def v_sub(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return np.clip(np.asarray(a, np.int64) - np.asarray(b, np.int64), FX_MIN, FX_MAX)


def v_mul(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    a = np.asarray(a, np.int64)
    b = np.asarray(b, np.int64)
    negative = (a < 0) != (b < 0)
    ua = np.abs(a)
    ub = np.abs(b)
    ah = ua >> FX_SHIFT
    al = ua - (ah << FX_SHIFT)
    bh = ub >> FX_SHIFT
    bl = ub - (bh << FX_SHIFT)
    mag = ((ah * bh) << FX_SHIFT) + ah * bl + al * bh + ((al * bl) >> FX_SHIFT)
    out = np.where(mag > FX_MAX, FX_MAX, mag)
    neg_out = np.where(mag >= _TWO31, FX_MIN, -mag)
    return np.where(negative, neg_out, out)


def v_div(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    a = np.asarray(a, np.int64)
    b = np.asarray(b, np.int64)
    negative = (a < 0) != (b < 0)
    ua = np.abs(a)
    ub = np.abs(b)
    safe = np.where(ub == 0, 1, ub)
    q = (ua << FX_SHIFT) // safe  # non-negative operands: floor == truncate
    pos = np.where(q > FX_MAX, FX_MAX, q)
    negq = np.where(q >= _TWO31, FX_MIN, -q)
    out = np.where(negative, negq, pos)
    # b == 0 saturates with the sign of the numerator, a == 0 gives 0
    zero_b = np.where(a > 0, FX_MAX, np.where(a < 0, FX_MIN, 0))
    out = np.where(ub == 0, zero_b, out)
    return np.where(a == 0, 0, out)


def v_isqrt(v: np.ndarray) -> np.ndarray:
    """Exact floor(sqrt(v)) elementwise.

    float64 sqrt is only correct to 53 bits, and the inputs reach 2**47, so the
    seed is corrected with exact integer comparisons afterwards. Two rounds of
    correction are enough: the float estimate is never off by more than one.
    """
    v = np.asarray(v, np.int64)
    r = np.sqrt(np.maximum(v, 0).astype(np.float64)).astype(np.int64)
    for _ in range(2):
        r = np.where(r * r > v, r - 1, r)
        r = np.where((r + 1) * (r + 1) <= v, r + 1, r)
    return np.where(v <= 0, 0, r)


def v_hypot(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    x = np.asarray(x, np.int64)
    y = np.asarray(y, np.int64)
    ax0 = np.abs(x)
    ay0 = np.abs(y)
    ax = ax0.copy()
    ay = ay0.copy()
    # The halving loop: bounded, and a lane only halves while it still needs to,
    # so the shift count is tracked per lane.
    shift = np.zeros_like(ax)
    for _ in range(8):
        need = (ax > HYPOT_SAFE) | (ay > HYPOT_SAFE)
        if not need.any():
            break
        ax = np.where(need, ax >> 1, ax)
        ay = np.where(need, ay >> 1, ay)
        shift = np.where(need, shift + 1, shift)
    r = v_isqrt(ax * ax + ay * ay) << shift
    r = np.where(r > FX_MAX, FX_MAX, r)
    # fx.js takes the zero shortcuts BEFORE the halving loop, so they read the
    # original magnitudes, not the halved ones.
    r = np.where(ax0 == 0, np.minimum(ay0, FX_MAX), r)
    return np.where(ay0 == 0, np.minimum(ax0, FX_MAX), r)
