"""State layout, constants and spec tables, loaded from python/layout.json.

Nothing in this module is typed by hand. layout.json is generated by
``node python/tools/dump-layout.mjs`` straight out of packages/core and
packages/bots, so a field that moves on the JS side moves here on the next
regeneration instead of silently becoming a wrong offset.

What IS asserted here is the shape the port depends on: the ball sharing the
x/z/vx/vz prefix with a player, the stride being wide enough, the header words
the port reads by name. A layout change the port has not been taught about
fails at import rather than at tick 1743.

The three private flag bits (FLAG_TOUCHING / FLAG_TACKLE_HELD / FLAG_DIVE_HELD)
are the only values not available from a JS export -- world.js keeps them
module-private. They are 1, 2 and 4, checked against the JS source text by
test_parity.py so a renumbering there cannot pass unnoticed.
"""

from __future__ import annotations

import json
from pathlib import Path
from types import MappingProxyType

PACKAGE_DIR = Path(__file__).resolve().parent
PYTHON_DIR = PACKAGE_DIR.parent
REPO_ROOT = PYTHON_DIR.parent
LAYOUT_PATH = PYTHON_DIR / "layout.json"
FIXTURES_DIR = PYTHON_DIR / "fixtures"


def load_layout(path: Path | str = LAYOUT_PATH) -> dict:
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


LAYOUT = load_layout()

CORE_VERSION = LAYOUT["coreVersion"]
STATE_MAGIC = LAYOUT["stateMagic"]
STATE_VERSION = LAYOUT["stateVersion"]
CONSTANTS_HASH = LAYOUT["constantsHash"]
CONSTANTS_HASH_INT = LAYOUT["constantsHashInt"]
TICK_RATE = LAYOUT["tickRate"]

HDR = MappingProxyType(dict(LAYOUT["header"]))
BALL_BASE = LAYOUT["ballBase"]
BALL_LEN = LAYOUT["ballLen"]
PLAYER_BASE = LAYOUT["playerBase"]
PLAYER_STRIDE = LAYOUT["playerStride"]
FIELD = MappingProxyType(dict(LAYOUT["field"]))
BTN = MappingProxyType(dict(LAYOUT["buttons"]))
C = MappingProxyType(dict(LAYOUT["constants"]))

# Header words, by the names world.js uses.
HDR_MAGIC = HDR["HDR_MAGIC"]
HDR_VERSION = HDR["HDR_VERSION"]
HDR_CONST_HASH = HDR["HDR_CONST_HASH"]
HDR_TICK = HDR["HDR_TICK"]
HDR_PLAYER_COUNT = HDR["HDR_PLAYER_COUNT"]
HDR_SCORE_0 = HDR["HDR_SCORE_0"]
HDR_SCORE_1 = HDR["HDR_SCORE_1"]
HDR_LAST_GOAL_TEAM = HDR["HDR_LAST_GOAL_TEAM"]
HDR_LAST_GOAL_TICK = HDR["HDR_LAST_GOAL_TICK"]
HDR_KICKOFF_TEAM = HDR["HDR_KICKOFF_TEAM"]
HDR_BALL_HOLDER = HDR["HDR_BALL_HOLDER"]
HDR_BALL_HOLD_TICKS = HDR["HDR_BALL_HOLD_TICKS"]
HDR_BALL_CURVE = HDR["HDR_BALL_CURVE"]
HDR_AFTERTOUCH_OWNER = HDR["HDR_AFTERTOUCH_OWNER"]
HDR_AFTERTOUCH_TICKS = HDR["HDR_AFTERTOUCH_TICKS"]
HDR_GRIEF_TEAM = HDR["HDR_GRIEF_TEAM"]
HDR_GRIEF_TICKS = HDR["HDR_GRIEF_TICKS"]
HDR_PITCH = HDR["HDR_PITCH"]
HDR_SETTINGS_HASH = HDR["HDR_SETTINGS_HASH"]
HDR_DURATION_TICKS = HDR["HDR_DURATION_TICKS"]
HDR_SCORE_LIMIT = HDR["HDR_SCORE_LIMIT"]
HDR_RULE_FLAGS = HDR["HDR_RULE_FLAGS"]
HDR_MATCH_STATE = HDR["HDR_MATCH_STATE"]
HDR_END_REASON = HDR["HDR_END_REASON"]
HDR_LEN = HDR["HDR_LEN"]

# Per-player slots.
P_X = FIELD["P_X"]
P_Z = FIELD["P_Z"]
P_VX = FIELD["P_VX"]
P_VZ = FIELD["P_VZ"]
P_TEAM = FIELD["P_TEAM"]
P_KICK_ARM = FIELD["P_KICK_ARM"]
P_KICK_CD = FIELD["P_KICK_CD"]
P_PREV_BUTTONS = FIELD["P_PREV_BUTTONS"]
P_ROLE = FIELD["P_ROLE"]
P_CHARGE = FIELD["P_CHARGE"]
P_CHARGE_REL = FIELD["P_CHARGE_REL"]
P_CHARGE_PWR = FIELD["P_CHARGE_PWR"]
P_TACKLE_ACTIVE = FIELD["P_TACKLE_ACTIVE"]
P_TACKLE_RECOV = FIELD["P_TACKLE_RECOV"]
P_TACKLE_CD = FIELD["P_TACKLE_CD"]
P_DIVE_ACTIVE = FIELD["P_DIVE_ACTIVE"]
P_DIVE_LOCK = FIELD["P_DIVE_LOCK"]
P_DIVE_DIR = FIELD["P_DIVE_DIR"]
P_CLEAR_CHARGE = FIELD["P_CLEAR_CHARGE"]
P_FLAGS = FIELD["P_FLAGS"]
P_TOUCH_CD = FIELD["P_TOUCH_CD"]

# world.js keeps these three private; test_parity.py greps the JS source to
# prove the numbers below are still the ones it uses.
FLAG_TOUCHING = 1
FLAG_TACKLE_HELD = 2
FLAG_DIVE_HELD = 4

BTN_KICK = BTN["KICK"]
BTN_CHARGE = BTN["CHARGE"]
BTN_CANCEL = BTN["CANCEL"]
BTN_TACKLE = BTN["TACKLE"]
BTN_CATCH = BTN["CATCH"]
BTN_THROW = BTN["THROW"]
BTN_CLEAR = BTN["CLEAR"]
BTN_DIVE = BTN["DIVE"]
BTN_TOUCH = BTN["TOUCH"]
BTN_MASK = 511

REACH = C["PLAYER_RADIUS"] + C["BALL_RADIUS"]

# Match rules.
_S = LAYOUT["settings"]
DEFAULT_SETTINGS = MappingProxyType(dict(_S["default"]))
SETTINGS_WORDS = _S["words"]
RULE_GOLDEN_GOAL = _S["ruleGoldenGoal"]
RULE_MERCY = _S["ruleMercy"]
RULE_KEEPERS = _S["ruleKeepers"]
RULE_MASK = RULE_GOLDEN_GOAL | RULE_MERCY | RULE_KEEPERS
MERCY_GOAL_DIFF = _S["mercyGoalDiff"]
MIN_DURATION_SECONDS = _S["minDurationSeconds"]
MAX_DURATION_SECONDS = _S["maxDurationSeconds"]
MIN_SCORE_LIMIT = _S["minScoreLimit"]
MAX_SCORE_LIMIT = _S["maxScoreLimit"]
MATCH_RUNNING = _S["matchRunning"]
MATCH_GOLDEN_GOAL = _S["matchGoldenGoal"]
MATCH_FINISHED = _S["matchFinished"]
END_NONE = _S["endNone"]
END_FULL_TIME = _S["endFullTime"]
END_SCORE_LIMIT = _S["endScoreLimit"]
END_MERCY = _S["endMercy"]
END_GOLDEN_GOAL = _S["endGoldenGoal"]

END_NAMES = ("none", "full-time", "score-limit", "mercy", "golden-goal")
PHASE_NAMES = ("running", "golden-goal", "finished")

# Pitch presets, index 0 deliberately empty (see matchRules.js).
PITCH_PRESETS = tuple(
    None if p is None else MappingProxyType(dict(p)) for p in LAYOUT["pitchPresets"]
)
PITCH_BY_ID = MappingProxyType({p["id"]: p for p in PITCH_PRESETS if p is not None})
DEFAULT_PITCH = PITCH_BY_ID["orta"]

OBSERVATION = LAYOUT["observation"]
ACTION = LAYOUT["action"]


def state_length(player_count: int) -> int:
    return PLAYER_BASE + player_count * PLAYER_STRIDE


def player_offset(i: int) -> int:
    return PLAYER_BASE + i * PLAYER_STRIDE


def _assert_shape() -> None:
    if not (P_X == 0 and P_Z == 1 and P_VX == 2 and P_VZ == 3):
        raise RuntimeError(
            "layout: the core no longer lays out x,z,vx,vz as the first four "
            "slots; every ball read in world.py assumes it does"
        )
    if BALL_BASE != HDR_LEN or PLAYER_BASE != BALL_BASE + BALL_LEN:
        raise RuntimeError("layout: header/ball/player bases are not contiguous")
    if PLAYER_STRIDE < max(FIELD.values()) + 1:
        raise RuntimeError("layout: player stride is smaller than the highest slot")
    if STATE_VERSION != 3:
        raise RuntimeError(
            f"layout: state version {STATE_VERSION} is not the v3 layout this port "
            "was written against; re-read world.js before regenerating"
        )
    missing = [
        k
        for k in (
            "KICK",
            "CHARGE",
            "CANCEL",
            "TACKLE",
            "CATCH",
            "THROW",
            "CLEAR",
            "DIVE",
            "TOUCH",
        )
        if k not in BTN
    ]
    if missing:
        raise RuntimeError(f"layout: BTN is missing {missing}")


_assert_shape()
